In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!cp /content/drive/MyDrive/image/images.zip -d /content/images.zip
!unzip -q images.zip

In [3]:
!rm /content/images.zip

In [4]:
import os
A=os.listdir('/content')
A

['.config', 'images', 'drive', 'sample_data']

In [5]:
import pandas as pd
import glob
import os
import numpy as np
import matplotlib.pyplot as plt
s='/content/images/*'
path=glob.glob(s)
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(data, key=alphanum_key)

path1=sorted_alphanumeric(path)
path1 = [item.replace('p','_') for item in path1]
data=pd.read_excel('/content/drive/MyDrive/image/data_c.xlsx')
data
len(path1)
print(path1)
type(path1)
path1=np.array(path1)
path1.shape
path1[0]

['/content/images/C_1_1_1.raw', '/content/images/C_1_1_16.raw', '/content/images/C_1_1_31.raw', '/content/images/C_1_1_46.raw', '/content/images/C_1_1_61.raw', '/content/images/C_1_1_76.raw', '/content/images/C_1_1_91.raw', '/content/images/C_1_1_106.raw', '/content/images/C_1_1_121.raw', '/content/images/C_1_1_136.raw', '/content/images/C_1_1_151.raw', '/content/images/C_1_1_166.raw', '/content/images/C_1_1_181.raw', '/content/images/C_1_1_196.raw', '/content/images/C_1_1_211.raw', '/content/images/C_1_1_226.raw', '/content/images/C_1_1_241.raw', '/content/images/C_1_1_256.raw', '/content/images/C_1_1_271.raw', '/content/images/C_1_1_286.raw', '/content/images/C_1_1_301.raw', '/content/images/C_1_16_1.raw', '/content/images/C_1_16_16.raw', '/content/images/C_1_16_31.raw', '/content/images/C_1_16_46.raw', '/content/images/C_1_16_61.raw', '/content/images/C_1_16_76.raw', '/content/images/C_1_16_91.raw', '/content/images/C_1_16_106.raw', '/content/images/C_1_16_121.raw', '/content/images

'/content/images/C_1_1_1.raw'

In [6]:
path1=np.array(path1)
data=np.array(data)

In [7]:
df=pd.DataFrame({'imgpath':path1,'Porosity':data[:,0],'throat radius':data[:,1],'pore radius':data[:,2],'pore_connection_number':data[:,3],'pore shape factor':data[:,4]})

In [8]:
df_new=df[df['Porosity'] <0.35 ]
df_new.shape
df_new

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.200016,0.000009,0.000013,1.92857,0.037024
1,/content/images/C_1_1_16.raw,0.211707,0.000008,0.000012,2.25000,0.036642
2,/content/images/C_1_1_31.raw,0.233293,0.000008,0.000013,1.96875,0.038013
3,/content/images/C_1_1_46.raw,0.264409,0.000009,0.000014,2.18182,0.039828
4,/content/images/C_1_1_61.raw,0.277295,0.000009,0.000014,2.27273,0.038306
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,0.136927,0.000008,0.000013,2.35443,0.036514
9257,/content/images/C_301_301_256.raw,0.136191,0.000008,0.000013,2.12658,0.036236
9258,/content/images/C_301_301_271.raw,0.147490,0.000008,0.000014,2.17722,0.033896
9259,/content/images/C_301_301_286.raw,0.161413,0.000008,0.000013,2.18987,0.035108


In [9]:
from sklearn.preprocessing import StandardScaler
import numpy as np
data1=np.array(df_new)
scaler = StandardScaler()
data1= scaler.fit_transform(data1[:,1:])
print(data1)
print(type(data1))
data1.shape

[[ 0.11455659  0.58493673  0.28969785 -0.82815281 -0.22691552]
 [ 0.27058416 -0.34306756 -0.15901557 -0.0260099  -0.34020621]
 [ 0.55866997 -0.05166937  0.52032542 -0.72788183  0.06680977]
 ...
 [-0.58645309 -0.39830083  0.62718527 -0.20763563 -1.1561657 ]
 [-0.40063734  0.06434896  0.10229779 -0.17606699 -0.79601231]
 [-0.15552552  0.3087704   1.25751387 -0.71308325 -2.46407987]]
<class 'numpy.ndarray'>


(7921, 5)

In [10]:
df=pd.DataFrame({'imgpath':df_new['imgpath'],'Porosity':data1[:,0],'throat radius':data1[:,1],'pore radius':data1[:,2],'pore_connection_number':data1[:,3],'pore shape factor':data1[:,4]})
df

,imgpath,Porosity,throat radius,pore radius,pore_connection_number,pore shape factor
0,/content/images/C_1_1_1.raw,0.114557,0.584937,0.289698,-0.828153,-0.226916
1,/content/images/C_1_1_16.raw,0.270584,-0.343068,-0.159016,-0.026010,-0.340206
2,/content/images/C_1_1_31.raw,0.558670,-0.051669,0.520325,-0.727882,0.066810
3,/content/images/C_1_1_46.raw,0.973943,0.745227,0.630089,-0.196156,0.606040
4,/content/images/C_1_1_61.raw,1.145919,0.514543,1.057970,0.030714,0.154056
...,...,...,...,...,...,...
9256,/content/images/C_301_301_241.raw,-0.727426,-0.487201,0.223571,0.234600,-0.378288
9257,/content/images/C_301_301_256.raw,-0.737249,-0.264275,0.454180,-0.334010,-0.460952
9258,/content/images/C_301_301_271.raw,-0.586453,-0.398301,0.627185,-0.207636,-1.156166
9259,/content/images/C_301_301_286.raw,-0.400637,0.064349,0.102298,-0.176067,-0.796012


In [11]:
data_t_general=df.sample(frac=0.9,random_state=1)
df_valid=data_t_general.sample(frac=0.15,random_state=2)
df_train=data_t_general.loc[~data_t_general.index.isin(df_valid.index)]
df_test =df.loc[~df.index.isin(data_t_general.index)]
len(df_train)

6060

In [12]:
def Data_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img = []
                y_batch=[]
                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    Porosity=np.array(df.Porosity)[idd]
                    throat_radius=np.array(df['throat radius'])[idd]
                    pore_radius=np.array(df['pore radius'])[idd]
                    pore_connection_number=np.array(df.pore_connection_number)[idd]
                    pore_shape_factor=np.array(df['pore shape factor'])[idd]
                    y_1=np.concatenate((Porosity, throat_radius,pore_radius,pore_connection_number, pore_shape_factor),axis=None)
                    y=np.array([y_1])
                    x_batch_img.append(img_1)
                    y_batch.append(y)


                x_batch_img = np.array(x_batch_img)
                y_batch= np.array(y_batch)
                y_batch=y_batch.reshape(-1,5)
              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img , y_batch

In [13]:
def Data_predict_generator(df, batch_size, augment=False):

    while True:

            for start in range(0, df.shape[0], batch_size):
                x_batch_img_2 = []

                end = min(start + batch_size, df.shape[0])

                for idd in range(start,end):
                    img = open(np.array(df.imgpath)[idd],'rb').read()
                    img_1=np.frombuffer(img,dtype=np.uint8)
                    img_1=img_1.reshape(100,100,100,1)
                    x_batch_img_2.append(img_1)



                x_batch_img_2 = np.array(x_batch_img_2)

              #y_batch = to_categorical(y_batch,5)
                yield x_batch_img_2

In [14]:
batch_size=10
train_gen= Data_generator(df_train,batch_size)
valid_gen= Data_generator(df_valid,batch_size)
train_gen_pre=Data_predict_generator(df_train,batch_size)
valid_gen_pre=Data_predict_generator(df_valid,batch_size)
test_gen= Data_generator(df_test,batch_size)
test_gen_pre=Data_predict_generator(df_test,batch_size)

In [15]:
import math
ntrain, nvalid, ntest = df_train.shape[0], df_valid.shape[0],  df_test.shape[0]
nbatches_train=math.ceil(df_train.shape[0]/batch_size)
nbatches_valid=math.ceil(df_valid.shape[0]/batch_size)
nbatches_test=math.ceil( df_test.shape[0]/batch_size)
nworkers=1

In [16]:
print(nbatches_valid,nbatches_train,nbatches_test)

107 606 80


In [17]:
from keras.models import Sequential
from keras.layers import Conv3D,MaxPooling3D,Dropout,Flatten,Dense,BatchNormalization,ReLU
from tensorflow.keras import initializers
from keras.callbacks import *
import tensorflow as tf

In [18]:
model=Sequential()
model.add(Conv3D(16,kernel_size=(7,7,7),input_shape=(100,100,100,1),padding="same",activation='relu',kernel_initializer=initializers.RandomNormal(stddev=0.01),))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(32,kernel_size=(5,5,5),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(64,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(128,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
#model.add(Dropout(0.2))
model.add(MaxPooling3D(pool_size=(2,2,2)))
model.add(Conv3D(256,kernel_size=(3,3,3),activation='relu',padding="same",kernel_initializer=initializers.RandomNormal(stddev=0.01)))
model.add(BatchNormalization())
model.add(MaxPooling3D(pool_size=(2,2,2)))
#model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(1024,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(512,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(5))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv3d (Conv3D)             (None, 100, 100, 100, 1   5504      
                             6)                                  
                                                                 
 batch_normalization (Batch  (None, 100, 100, 100, 1   64        
 Normalization)              6)                                  
                                                                 
 max_pooling3d (MaxPooling3  (None, 50, 50, 50, 16)    0         
 D)                                                              
                                                                 
 conv3d_1 (Conv3D)           (None, 50, 50, 50, 32)    64032     
                                                                 
 batch_normalization_1 (Bat  (None, 50, 50, 50, 32)    128       
 chNormalization)                                       

In [19]:
import os
checkpoint_path="/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-{epoch:03d}.ckpt"
#os.makedirs("/content/drive/MyDrive/image/porosity_filtering/training_5layers", exist_ok=True)
#ckpt_callback = ModelCheckpoint(filepath='/content/drive/MyDrive/image/porosity_filtering/training_model_5layers/weights.{epoch:02d}-{val_loss:.2f}.hdf5', monitor='val_loss')
cp_callback=ModelCheckpoint(filepath=checkpoint_path,save_weights_only=True,verbose=1)

In [20]:
csvlogger=CSVLogger('/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/Training_189.log')

In [21]:
opt = tf.keras.optimizers.Adam(learning_rate=0.0005)
model.compile(opt,loss='mse',metrics=['mse'])

In [ ]:
history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])

Epoch 1/200


<ipython-input-22-2be0de0fe96b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger])



Epoch 1: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-001.ckpt
606/606 - 381s - loss: 2.3660 - mse: 2.3660 - val_loss: 60.4507 - val_mse: 60.4507 - 381s/epoch - 628ms/step
Epoch 2/200

Epoch 2: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-002.ckpt
606/606 - 336s - loss: 1.0187 - mse: 1.0187 - val_loss: 66.2787 - val_mse: 66.2787 - 336s/epoch - 554ms/step
Epoch 3/200

Epoch 3: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-003.ckpt
606/606 - 335s - loss: 0.6078 - mse: 0.6078 - val_loss: 0.8930 - val_mse: 0.8930 - 335s/epoch - 553ms/step
Epoch 4/200

Epoch 4: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-004.ckpt
606/606 - 335s - loss: 0.4394 - mse: 0.4394 - val_loss: 1.4190 - val_mse: 1.4190 - 335s/epoch - 553ms/step
Epoch 5/200

Epo

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-040.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=40)

<ipython-input-23-ba9e5818ed4d>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=40)


Epoch 41/200

Epoch 41: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-041.ckpt
606/606 - 384s - loss: 0.1581 - mse: 0.1581 - val_loss: 0.2086 - val_mse: 0.2086 - 384s/epoch - 633ms/step
Epoch 42/200

Epoch 42: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-042.ckpt
606/606 - 317s - loss: 0.1563 - mse: 0.1563 - val_loss: 0.1553 - val_mse: 0.1553 - 317s/epoch - 524ms/step
Epoch 43/200

Epoch 43: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-043.ckpt
606/606 - 317s - loss: 0.1558 - mse: 0.1558 - val_loss: 0.2043 - val_mse: 0.2043 - 317s/epoch - 524ms/step
Epoch 44/200

Epoch 44: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-044.ckpt
606/606 - 336s - loss: 0.1551 - mse: 0.1551 - val_loss: 0.1529 - val_mse: 0.1529 - 336s/epoch - 554ms/step


In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/training_model_weights/cp-108.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=108)

Epoch 109/200


<ipython-input-23-54cce96ec699>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=108)



Epoch 109: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-109.ckpt
606/606 - 376s - loss: 0.1306 - mse: 0.1306 - val_loss: 0.1127 - val_mse: 0.1127 - 376s/epoch - 621ms/step
Epoch 110/200

Epoch 110: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-110.ckpt
606/606 - 329s - loss: 0.1304 - mse: 0.1304 - val_loss: 0.1064 - val_mse: 0.1064 - 329s/epoch - 542ms/step
Epoch 111/200

Epoch 111: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-111.ckpt
606/606 - 329s - loss: 0.1298 - mse: 0.1298 - val_loss: 0.1108 - val_mse: 0.1108 - 329s/epoch - 543ms/step
Epoch 112/200

Epoch 112: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-112.ckpt
606/606 - 309s - loss: 0.1292 - mse: 0.1292 - val_loss: 0.1158 - val_mse: 0.1158 - 309s/epoch - 510ms/step
Epoch 

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-115.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=115)

Epoch 116/200


<ipython-input-23-4dbef963fa09>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=115)



Epoch 116: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-116.ckpt
606/606 - 363s - loss: 0.1283 - mse: 0.1283 - val_loss: 0.1120 - val_mse: 0.1120 - 363s/epoch - 599ms/step
Epoch 117/200

Epoch 117: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-117.ckpt
606/606 - 310s - loss: 0.1293 - mse: 0.1293 - val_loss: 0.1075 - val_mse: 0.1075 - 310s/epoch - 512ms/step
Epoch 118/200

Epoch 118: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-118.ckpt
606/606 - 310s - loss: 0.1285 - mse: 0.1285 - val_loss: 0.1046 - val_mse: 0.1046 - 310s/epoch - 511ms/step
Epoch 119/200

Epoch 119: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-119.ckpt
606/606 - 329s - loss: 0.1291 - mse: 0.1291 - val_loss: 0.1075 - val_mse: 0.1075 - 329s/epoch - 543ms/step
Epoch 

In [ ]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-130.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=130)

Epoch 131/200


<ipython-input-23-94637ded49ca>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=130)



Epoch 131: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-131.ckpt
606/606 - 356s - loss: 0.1276 - mse: 0.1276 - val_loss: 0.1105 - val_mse: 0.1105 - 356s/epoch - 587ms/step
Epoch 132/200

Epoch 132: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-132.ckpt
606/606 - 302s - loss: 0.1273 - mse: 0.1273 - val_loss: 0.1069 - val_mse: 0.1069 - 302s/epoch - 498ms/step
Epoch 133/200

Epoch 133: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-133.ckpt
606/606 - 302s - loss: 0.1271 - mse: 0.1271 - val_loss: 0.1139 - val_mse: 0.1139 - 302s/epoch - 498ms/step
Epoch 134/200

Epoch 134: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-134.ckpt
606/606 - 302s - loss: 0.1275 - mse: 0.1275 - val_loss: 0.1127 - val_mse: 0.1127 - 302s/epoch - 498ms/step
Epoch 

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/training_model_weights/cp-180.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=180)

Epoch 181/200


<ipython-input-23-d0589dc395fd>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=180)



Epoch 181: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-181.ckpt
606/606 - 406s - loss: 0.1246 - mse: 0.1246 - val_loss: 0.1025 - val_mse: 0.1025 - 406s/epoch - 670ms/step
Epoch 182/200

Epoch 182: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-182.ckpt
606/606 - 340s - loss: 0.1255 - mse: 0.1255 - val_loss: 0.1009 - val_mse: 0.1009 - 340s/epoch - 561ms/step
Epoch 183/200

Epoch 183: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-183.ckpt
606/606 - 321s - loss: 0.1237 - mse: 0.1237 - val_loss: 0.1020 - val_mse: 0.1020 - 321s/epoch - 530ms/step
Epoch 184/200

Epoch 184: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-184.ckpt
606/606 - 321s - loss: 0.1253 - mse: 0.1253 - val_loss: 0.1083 - val_mse: 0.1083 - 321s/epoch - 529ms/step
Epoch 

In [22]:
wieght='/content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-190.ckpt'
model.load_weights(wieght)

In [ ]:
history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=190)

<ipython-input-23-b0b03c26e90b>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history1=model.fit_generator(train_gen, steps_per_epoch=nbatches_train, epochs=200, verbose=2, validation_data=valid_gen, validation_steps=nbatches_valid,callbacks=[cp_callback,csvlogger],initial_epoch=190)


Epoch 191/200

Epoch 191: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-191.ckpt
606/606 - 369s - loss: 0.1246 - mse: 0.1246 - val_loss: 0.1020 - val_mse: 0.1020 - 369s/epoch - 609ms/step
Epoch 192/200

Epoch 192: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-192.ckpt
606/606 - 338s - loss: 0.1241 - mse: 0.1241 - val_loss: 0.1030 - val_mse: 0.1030 - 338s/epoch - 558ms/step
Epoch 193/200

Epoch 193: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-193.ckpt
606/606 - 338s - loss: 0.1234 - mse: 0.1234 - val_loss: 0.1309 - val_mse: 0.1309 - 338s/epoch - 557ms/step
Epoch 194/200

Epoch 194: saving model to /content/drive/MyDrive/image/porosity_filtering/learnin_rate/0.0005/training_model_weights/cp-194.ckpt
606/606 - 318s - loss: 0.1243 - mse: 0.1243 - val_loss: 0.1106 - val_mse: 0.1106 - 318s/epoch - 524